name: Build & test reutilizable
on:
    workflow_call:
        inputs:
            java-version:
                required: true
                type: string
jobs:
    build-y-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6.1.0
            - name: Configurar JDK ${{ inputs.java-version }}
              uses: actions/setup-java@v6.0.1
              with:
                  distribution: 'temurin'
                  java-version: '${{ inputs.java-version }}'
            - name: Cache de paquetes Maven
              uses: actions/cache@v4
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            - name: Compilar el proyecto y pruebas
              run: mvn clean verify
              env:
                DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                NOMBRE_USR: ${{ secrets.NOMBRE_USR }}
            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v7.0.1
              with:
                    # Artifact name. If the `archive` input is `false`, the name of the file uploaded will be the artifact name.
                    name: springboot-app
                    # A file, directory or wildcard pattern that describes what to upload.
                    path: target/*.jar